/**
 * @file test_ModeToExportIntegration.cpp
 * @brief HITO-04C: Mode-to-Export Integration Test Suite (ST-99 to ST-107).
 *
 * Demonstrates end-to-end convergence of AutomatedMidi and ManualOperator
 * campaigns into the single, shared ReportExportService pipeline.
 */

#include <catch2/catch_test_macros.hpp>
#include <filesystem>
#include <fstream>
#include <chrono>
#include <atomic>
#include <thread>
#include <nlohmann/json.hpp>

#include "core/ProfilingSequencer.h"
#include "hardware/MockHardwareController.h"
#include "hardware/ManualAnalogueController.h"
#include "export/ReportExportService.h"
#include "gui/session/ProfilingSessionContracts.h"

using namespace abdaudiolab;
using namespace abdaudiolab::core;
using namespace abdaudiolab::exporting;
using namespace abdaudiolab::gui::session;

// RAII unique temp directory for integration test artifacts
struct IntegrationTempDirectory
{
    std::filesystem::path path;

    IntegrationTempDirectory(const std::string& prefix = "mode_export_test")
    {
        auto tick = std::chrono::system_clock::now().time_since_epoch().count();
        path = std::filesystem::temp_directory_path()
             / "abdaudiolab_e2e"
             / (prefix + "_" + std::to_string(tick));
        std::error_code ec;
        std::filesystem::remove_all(path, ec);
        std::filesystem::create_directories(path, ec);
    }

    ~IntegrationTempDirectory()
    {
        std::error_code ec;
        std::filesystem::remove_all(path, ec);
    }

    IntegrationTempDirectory(const IntegrationTempDirectory&) = delete;
    IntegrationTempDirectory& operator=(const IntegrationTempDirectory&) = delete;
};

// ===========================================================================
// ST-99 — Campaña AutomatedMidi completa -> EvaluationSnapshot -> Exportación real
// ===========================================================================
TEST_CASE("ST-99: AutomatedMidi campaign produces exportable session and valid ProductionPackage", "[integration][mode_to_export][ST-99]")
{
    IntegrationTempDirectory runDir("st99_run");
    IntegrationTempDirectory exportDir("st99_export");

    // 1. Setup real audio engine and automated mock hardware
    audio::LabAudioEngine audioEngine;
    hardware::MockHardwareController mockHw;
    ProfilingSequencer sequencer(audioEngine, mockHw);

    ProfilingSession session;
    ProfilingMetadata meta;
    meta.hardwareName = "DEXED_AUTOMATED_SIM";
    meta.targetModule = "VCF";
    meta.operatorMode = "AUTOMATED_MIDI_NOTES";
    session.setMetadata(meta);

    TestCase tc;
    tc.testId = "ST99_AUTO_TRIAL_01";
    tc.functionalBlockType = "SpectrumFilter";
    tc.stimulusType = audio::StimulusType::Silence;
    tc.stimulusDurationSec = 0.05;
    tc.isAutonomousSynth = true;
    tc.midiChannel = 1;
    tc.midiNoteNumber = 60; // C4
    tc.midiVelocity = 0.80f;
    tc.noteGateDurationSec = 0.04f;
    tc.numPasses = 1;
    tc.stabilizationWaitMs = 10.0;
    session.addTestCase(tc);

    juce::File juceRunDir(runDir.path.string());
    mockHw.clearSentMessages();

    // 2. Execute sequencer campaign
    REQUIRE(sequencer.startSession(session, juceRunDir, "st99_campaign"));
    REQUIRE(sequencer.waitForThreadToExit(8000));
    REQUIRE(sequencer.getCurrentState() == SequencerState::Finished);

    // 3. Verify real measured points generated by the sequencer
    const auto& measured = sequencer.getMeasuredPoints();
    REQUIRE_FALSE(measured.empty());
    REQUIRE(measured.front().testId == "ST99_AUTO_TRIAL_01");

    // 4. Verify ExportReadiness guard pass on completed session snapshot
    ProfilingSessionSnapshot snap;
    snap.sessionStatus = ProfilingSessionStatus::Completed;
    snap.workflowStage = ProfilingWorkflowStage::ReviewResults;
    snap.exportOptions.canExportCpp = true;
    snap.excitation.excitationMode = gui::session::ExcitationMode::AutomatedMidi;
    snap.excitation.targetControlMode = TargetControlMode::Vst3;
    snap.excitation.status = RecipeStatus::Valid;

    ExportReadiness readiness = evaluateExportReadinessFromSnapshot(snap);
    REQUIRE(readiness.canProceed());

    // 5. Execute unified export through ReportExportService
    ReportExportRequest req;
    req.manifest.hardwareId = "dexed_vst3";
    req.manifest.hardwareDisplayName = "Dexed DX7 VST3";
    req.manifest.activeFunctionId = "vcf_ladder";
    req.manifest.activeFunctionName = "Resonant Lowpass";
    req.manifest.targetModule = "VCF";
    req.baseFileName = "Dexed_Approved_Model";
    req.destinationDirectory = exportDir.path;
    req.context.sampleRate = 48000.0;
    req.measuredPoints = measured;
    req.options.includeProductionPackage = true;
    req.options.includeHtmlCertification = false;

    ReportExportResult res = ReportExportService::exportReport(req);
    REQUIRE(res.succeeded());
    REQUIRE(res.status == ReportExportStatus::Success);
    REQUIRE(res.artifacts.size() == 4);

    for (const auto& art : res.artifacts)
    {
        REQUIRE(std::filesystem::exists(art.publishedPath));
        REQUIRE(std::filesystem::file_size(art.publishedPath) > 0);
    }
}

// ===========================================================================
// ST-100 — Campaña ManualOperator completa -> EvaluationSnapshot -> Exportación real
// ===========================================================================
TEST_CASE("ST-100: ManualOperator campaign produces exportable session and valid ProductionPackage", "[integration][mode_to_export][ST-100]")
{
    IntegrationTempDirectory runDir("st100_run");
    IntegrationTempDirectory exportDir("st100_export");

    // 1. Setup real audio engine and manual analogue hardware controller
    audio::LabAudioEngine audioEngine;
    hardware::ManualAnalogueController manualHw("Analog Moog Ladder VCF");
    ProfilingSequencer sequencer(audioEngine, manualHw);

    ProfilingSession session;
    ProfilingMetadata meta;
    meta.hardwareName = "MOOG_MODULAR_ANALOGUE";
    meta.targetModule = "VCF";
    meta.operatorMode = "MANUAL_OPERATOR_PROMPT";
    session.setMetadata(meta);

    TestCase tc;
    tc.testId = "ST100_MANUAL_TRIAL_01";
    tc.functionalBlockType = "SpectrumFilter";
    // Using LogFarinaSweep so hardware->isAutomatic() == false triggers WaitingForOperator
    tc.stimulusType = audio::StimulusType::LogFarinaSweep;
    tc.stimulusDurationSec = 0.05;
    tc.isAutonomousSynth = false;
    tc.numPasses = 1;
    tc.stabilizationWaitMs = 10.0;

    ParameterStep pStep;
    pStep.paramName = "Cutoff";
    pStep.normalizedValue = 0.50f;
    tc.parameterSteps.push_back(pStep);
    session.addTestCase(tc);

    juce::File juceRunDir(runDir.path.string());

    // 2. Start sequencer and handle interactive WaitingForOperator transition
    std::atomic<bool> sawWaitingForOperator { false };
    std::atomic<bool> sawStabilization { false };

    sequencer.setProgressCallback([&](float /*prog*/, const juce::String& /*task*/, SequencerState state) {
        if (state == SequencerState::WaitingForOperator)
            sawWaitingForOperator.store(true, std::memory_order_release);
        if (state == SequencerState::WaitForStabilization)
            sawStabilization.store(true, std::memory_order_release);
    });

    REQUIRE(sequencer.startSession(session, juceRunDir, "st100_campaign"));

    // Poll until sequencer enters WaitingForOperator, then operator confirms step
    int waitCounter = 0;
    while (sequencer.getCurrentState() != SequencerState::WaitingForOperator && waitCounter < 200)
    {
        juce::Thread::sleep(20);
        ++waitCounter;
    }
    REQUIRE(sequencer.getCurrentState() == SequencerState::WaitingForOperator);

    // Operator confirms setting: unblocks WaitingForOperator -> WaitForStabilization -> Finished
    sequencer.confirmOperatorStep();

    REQUIRE(sequencer.waitForThreadToExit(8000));
    REQUIRE(sequencer.getCurrentState() == SequencerState::Finished);

    // 3. Verify real measured points generated by the sequencer
    const auto& measured = sequencer.getMeasuredPoints();
    REQUIRE_FALSE(measured.empty());
    REQUIRE(measured.front().testId == "ST100_MANUAL_TRIAL_01");

    // 4. Verify ExportReadiness guard pass on completed session snapshot
    ProfilingSessionSnapshot snap;
    snap.sessionStatus = ProfilingSessionStatus::Completed;
    snap.workflowStage = ProfilingWorkflowStage::ReviewResults;
    snap.exportOptions.canExportCpp = true;
    snap.excitation.excitationMode = gui::session::ExcitationMode::ManualOperator;
    snap.excitation.targetControlMode = TargetControlMode::NoDigitalControl;
    snap.excitation.status = RecipeStatus::Valid;

    ExportReadiness readiness = evaluateExportReadinessFromSnapshot(snap);
    REQUIRE(readiness.canProceed());

    // 5. Execute unified export through ReportExportService
    ReportExportRequest req;
    req.manifest.hardwareId = "analog_eurorack_vcf";
    req.manifest.hardwareDisplayName = "Moog Ladder Eurorack";
    req.manifest.activeFunctionId = "vcf_manual";
    req.manifest.activeFunctionName = "VCF Cutoff Sweep";
    req.manifest.targetModule = "VCF";
    req.baseFileName = "Moog_Approved_Model";
    req.destinationDirectory = exportDir.path;
    req.context.sampleRate = 48000.0;
    req.context.operatorNotes = "Calibrated at 22C, manual knob adjustment confirmed by operator-01.";
    req.measuredPoints = measured;
    req.options.includeProductionPackage = true;
    req.options.includeHtmlCertification = false;

    ReportExportResult res = ReportExportService::exportReport(req);
    REQUIRE(res.succeeded());
    REQUIRE(res.status == ReportExportStatus::Success);
    REQUIRE(res.artifacts.size() == 4);

    for (const auto& art : res.artifacts)
    {
        REQUIRE(std::filesystem::exists(art.publishedPath));
        REQUIRE(std::filesystem::file_size(art.publishedPath) > 0);
    }
}

// ===========================================================================
// ST-101 — Campaña Manual sin confirmación de operador -> exportación bloqueada
// ===========================================================================
TEST_CASE("ST-101: ManualOperator campaign without operator confirmation is blocked from export", "[integration][mode_to_export][ST-101]")
{
    // Una sesión manual que NO ha completado su ciclo de vida
    // debe ser bloqueada por la guarda de sesión no completada.

    ProfilingSessionSnapshot snap;
    snap.sessionStatus  = ProfilingSessionStatus::Profiling; // En progreso, no completada
    snap.workflowStage  = ProfilingWorkflowStage::ProfilingActive;
    snap.exportOptions.canExportCpp = true;
    snap.excitation.excitationMode  = gui::session::ExcitationMode::ManualOperator;
    snap.excitation.status          = RecipeStatus::Valid;

    ExportReadiness readiness = evaluateExportReadinessFromSnapshot(snap);

    // Guarda 1: sessionCompleted == false -> Blocked
    REQUIRE_FALSE(readiness.sessionCompleted);
    REQUIRE_FALSE(readiness.canProceed());
    REQUIRE(readiness.decision == ExportReadiness::Decision::Blocked);
    REQUIRE_FALSE(readiness.blockReason.empty());

    // Verificar que el bloqueo es por sesión no completada, no por otro motivo
    // El snapshot está en Profiling -> la guarda 1 debe dispararse antes que cualquier otra
    REQUIRE(snap.sessionStatus == ProfilingSessionStatus::Profiling);
}

// ===========================================================================
// ST-102 — Campaña MIDI incompleta -> exportación bloqueada
// ===========================================================================
TEST_CASE("ST-102: AutomatedMidi campaign with incomplete session is blocked from export", "[integration][mode_to_export][ST-102]")
{
    // Simulamos tres estados de sesión que deben bloquear la exportación.
    // Ninguno de ellos es Completed, EvaluationLoadedForReview, Exported
    // ni corresponde al stage ReviewResults.

    const std::vector<std::pair<ProfilingSessionStatus, ProfilingWorkflowStage>> incompleteStates =
    {
        { ProfilingSessionStatus::Idle,      ProfilingWorkflowStage::TargetSelection },
        { ProfilingSessionStatus::Profiling, ProfilingWorkflowStage::ProfilingActive },
        { ProfilingSessionStatus::Paused,    ProfilingWorkflowStage::ProfilingActive }
    };

    for (const auto& [status, stage] : incompleteStates)
    {
        ProfilingSessionSnapshot snap;
        snap.sessionStatus  = status;
        snap.workflowStage  = stage;
        snap.exportOptions.canExportCpp = true;
        snap.excitation.excitationMode  = gui::session::ExcitationMode::AutomatedMidi;
        snap.excitation.targetControlMode = TargetControlMode::Vst3;
        snap.excitation.status          = RecipeStatus::Valid;

        ExportReadiness readiness = evaluateExportReadinessFromSnapshot(snap);

        // Guarda 1 debe dispararse: sesión no completada
        REQUIRE_FALSE(readiness.sessionCompleted);
        REQUIRE_FALSE(readiness.canProceed());
        REQUIRE(readiness.decision == ExportReadiness::Decision::Blocked);
        REQUIRE_FALSE(readiness.blockReason.empty());
    }
}

// ===========================================================================
// ST-103 — Receta y procedencia registradas fielmente en manifest.json
// ===========================================================================
TEST_CASE("ST-103: Manifest preserves provenance and hardware identity for both modes", "[integration][mode_to_export][ST-103]")
{
    IntegrationTempDirectory tempDir("st103_manifest");

    // Generamos dos paquetes con identidades de modo explícitas
    ReportExportRequest reqAuto;
    reqAuto.manifest.hardwareId = "AIRA_TB3_TOUCH";
    reqAuto.manifest.hardwareDisplayName = "Roland AIRA TB-3";
    reqAuto.manifest.activeFunctionId = "synth_saw";
    reqAuto.baseFileName = "AutoTB3";
    reqAuto.destinationDirectory = tempDir.path / "auto";
    reqAuto.options.includeProductionPackage = true;
    reqAuto.options.includeHtmlCertification = false;

    MeasuredPoint ptA;
    ptA.pointId = "P_AUTO_1";
    ptA.blockType = "VCF";
    reqAuto.measuredPoints.push_back(ptA);

    ReportExportResult resAuto = ReportExportService::exportReport(reqAuto);
    REQUIRE(resAuto.succeeded());

    ReportExportRequest reqManual;
    reqManual.manifest.hardwareId = "EURORACK_DOEPFER_A120";
    reqManual.manifest.hardwareDisplayName = "Doepfer A-120 VCF";
    reqManual.manifest.activeFunctionId = "ladder_lowpass";
    reqManual.baseFileName = "ManualA120";
    reqManual.destinationDirectory = tempDir.path / "manual";
    reqManual.context.operatorNotes = "Operator step confirmed. Knob at 1.2 kHz.";
    reqManual.options.includeProductionPackage = true;
    reqManual.options.includeHtmlCertification = false;

    MeasuredPoint ptM;
    ptM.pointId = "P_MANUAL_1";
    ptM.blockType = "VCF";
    reqManual.measuredPoints.push_back(ptM);

    ReportExportResult resManual = ReportExportService::exportReport(reqManual);
    REQUIRE(resManual.succeeded());

    // Leemos ambos manifest.json generados
    auto autoManifestPath = tempDir.path / "auto" / "AutoTB3_manifest.json";
    auto manualManifestPath = tempDir.path / "manual" / "ManualA120_manifest.json";

    REQUIRE(std::filesystem::exists(autoManifestPath));
    REQUIRE(std::filesystem::exists(manualManifestPath));

    std::ifstream inAuto(autoManifestPath);
    nlohmann::json jsonAuto = nlohmann::json::parse(inAuto);

    std::ifstream inManual(manualManifestPath);
    nlohmann::json jsonManual = nlohmann::json::parse(inManual);

    // Verificación de contrato común
    REQUIRE(jsonAuto["sessionManifestVersion"] == "2.0");
    REQUIRE(jsonManual["sessionManifestVersion"] == "2.0");

    // Verificación de procedencia diferenciada preservada
    REQUIRE(jsonAuto["hardware"]["id"] == "AIRA_TB3_TOUCH");
    REQUIRE(jsonAuto["hardware"]["deviceType"] == "AUTOMATED_SYSEX");

    REQUIRE(jsonManual["hardware"]["id"] == "EURORACK_DOEPFER_A120");
    REQUIRE(jsonManual["hardware"]["deviceType"] == "MANUAL_EURORACK");
    REQUIRE(jsonManual["laboratoryConditions"]["operatorNotes"] == "Operator step confirmed. Knob at 1.2 kHz.");
}

// ===========================================================================
// ST-104 — Manifest modo Manual: operatorNotes presente, sin sequenceHash MIDI
// ===========================================================================
TEST_CASE("ST-104: ManualOperator manifest contains operatorNotes and no MIDI sequenceHash", "[integration][mode_to_export][ST-104]")
{
    IntegrationTempDirectory tempDir("st104_manual_manifest");

    ReportExportRequest req;
    req.manifest.hardwareId          = "EURORACK_MOOG_VCF";
    req.manifest.hardwareDisplayName  = "Moog Ladder Filter Eurorack";
    req.manifest.activeFunctionId     = "vcf_manual_sweep";
    req.baseFileName                  = "ManualSweep";
    req.destinationDirectory          = tempDir.path;
    req.context.operatorNotes         = "Operator confirmed at step 3. Knob set to 880 Hz cutoff.";
    req.context.ambientTemperatureC   = 22.5;
    req.options.includeProductionPackage  = true;
    req.options.includeHtmlCertification  = false;

    MeasuredPoint pt;
    pt.pointId = "P_MANUAL_ST104";
    pt.blockType = "VCF";
    req.measuredPoints.push_back(pt);

    ReportExportResult res = ReportExportService::exportReport(req);
    REQUIRE(res.succeeded());

    auto manifestPath = tempDir.path / "ManualSweep_manifest.json";
    REQUIRE(std::filesystem::exists(manifestPath));

    std::ifstream in(manifestPath);
    nlohmann::json j = nlohmann::json::parse(in);

    // ST-104: operatorNotes debe estar presente en laboratoryConditions
    REQUIRE(j.contains("laboratoryConditions"));
    REQUIRE(j["laboratoryConditions"]["operatorNotes"] == "Operator confirmed at step 3. Knob set to 880 Hz cutoff.");
    REQUIRE(j["laboratoryConditions"]["ambientTemperatureC"].get<double>() == 22.5);

    // ST-104: el manifest NO debe contener un campo MIDI sequenceHash
    // (ese campo solo existe en manifests de modo AutomatedMidi)
    REQUIRE_FALSE(j.contains("midiSequenceHash"));
    REQUIRE_FALSE(j.contains("sequenceHash"));

    // ST-104: hardware.deviceType debe identificar hardware analógico
    REQUIRE(j["hardware"]["deviceType"] == "MANUAL_EURORACK");
    REQUIRE(j["hardware"]["id"] == "EURORACK_MOOG_VCF");
}

// ===========================================================================
// ===========================================================================
// ST-105 — Manifest modo AutomatedSysEx: totalPointsMeasured y hardware.id correctos
// Fixture: Roland AIRA TB-3 SysEx
//   - excitationMode:    AutomatedSysEx
//   - targetControlMode: MidiSysEx
//   - deviceType:        AUTOMATED_SYSEX
// ===========================================================================
TEST_CASE("ST-105: AutomatedSysEx manifest contains correct totalPointsMeasured and hardware identity", "[integration][mode_to_export][ST-105]")
{
    IntegrationTempDirectory tempDir("st105_auto_manifest");

    // Exportación con múltiples puntos medidos simulando una campaña SysEx real
    ReportExportRequest req;
    req.manifest.hardwareId          = "AIRA_TB3_SYSEX_SEQ";
    req.manifest.hardwareDisplayName  = "Roland AIRA TB-3 SysEx";
    req.manifest.activeFunctionId     = "osc_sawtooth_sweep";
    req.manifest.activeFunctionName   = "Sawtooth VCO Sweep";
    req.baseFileName                  = "AIRASawSweep";
    req.destinationDirectory          = tempDir.path;
    req.options.includeProductionPackage  = true;
    req.options.includeHtmlCertification  = false;

    // 5 puntos medidos (simulación de grid factorial SysEx)
    for (int i = 0; i < 5; ++i)
    {
        MeasuredPoint pt;
        pt.pointId = "P_AUTO_" + std::to_string(i);
        pt.blockType = "VCO";
        req.measuredPoints.push_back(pt);
    }

    ReportExportResult res = ReportExportService::exportReport(req);
    REQUIRE(res.succeeded());

    auto manifestPath = tempDir.path / "AIRASawSweep_manifest.json";
    REQUIRE(std::filesystem::exists(manifestPath));

    std::ifstream in(manifestPath);
    nlohmann::json j = nlohmann::json::parse(in);

    // ST-105: Conteo exacto de puntos medidos
    REQUIRE(j["totalPointsMeasured"] == 5);

    // ST-105: Identidad de hardware preservada con fidelidad
    REQUIRE(j["hardware"]["id"] == "AIRA_TB3_SYSEX_SEQ");
    REQUIRE(j["hardware"]["name"] == "Roland AIRA TB-3 SysEx");
    REQUIRE(j["hardware"]["functionId"] == "osc_sawtooth_sweep");
    REQUIRE(j["hardware"]["functionName"] == "Sawtooth VCO Sweep");

    // ST-105: deviceType debe identificar origen automatizado SysEx (contiene "AIRA")
    REQUIRE(j["hardware"]["deviceType"] == "AUTOMATED_SYSEX");

    // ST-105: Esquema del manifest es la versión canónica 2.0
    REQUIRE(j["sessionManifestVersion"] == "2.0");

    // ST-105: No debe contener operatorNotes (campaña no-manual)
    // El campo existe pero debe estar vacío (operatorNotes por defecto es "")
    REQUIRE(j["laboratoryConditions"]["operatorNotes"] == "");
}

// ===========================================================================
// ST-106 — Ambos modos generan el mismo conjunto canónico de artefactos obligatorios
// ===========================================================================
TEST_CASE("ST-106: Both modes produce identical required production package artifacts", "[integration][mode_to_export][ST-106]")
{
    IntegrationTempDirectory tempDir("st106_artifacts");

    // Configuración A: Automatizado
    ReportExportRequest reqAuto;
    reqAuto.manifest.hardwareId = "AIRA_SYNTH";
    reqAuto.baseFileName = "AutoProd";
    reqAuto.destinationDirectory = tempDir.path / "auto";
    reqAuto.options.includeProductionPackage = true;
    reqAuto.options.includeHtmlCertification = false;
    MeasuredPoint p1; p1.pointId = "P1"; reqAuto.measuredPoints.push_back(p1);

    ReportExportResult resAuto = ReportExportService::exportReport(reqAuto);
    REQUIRE(resAuto.succeeded());

    // Configuración B: Manual
    ReportExportRequest reqManual;
    reqManual.manifest.hardwareId = "MANUAL_VCF";
    reqManual.baseFileName = "ManualProd";
    reqManual.destinationDirectory = tempDir.path / "manual";
    reqManual.options.includeProductionPackage = true;
    reqManual.options.includeHtmlCertification = false;
    MeasuredPoint p2; p2.pointId = "P2"; reqManual.measuredPoints.push_back(p2);

    ReportExportResult resManual = ReportExportService::exportReport(reqManual);
    REQUIRE(resManual.succeeded());

    // Extraemos tipos de artefactos de ambos resultados
    std::vector<ReportArtifactKind> kindsAuto;
    for (const auto& a : resAuto.artifacts) kindsAuto.push_back(a.kind);

    std::vector<ReportArtifactKind> kindsManual;
    for (const auto& a : resManual.artifacts) kindsManual.push_back(a.kind);

    // Contrato ST-106: Mismo conjunto de artefactos obligatorios producidos
    REQUIRE(kindsAuto == kindsManual);
    REQUIRE(kindsAuto.size() == 4);

    // Los 4 artefactos canónicos obligatorios
    REQUIRE(kindsAuto[0] == ReportArtifactKind::CppLutHeader);
    REQUIRE(kindsAuto[1] == ReportArtifactKind::TelemetryJson);
    REQUIRE(kindsAuto[2] == ReportArtifactKind::CertificationHtml);
    REQUIRE(kindsAuto[3] == ReportArtifactKind::SessionManifestJson);
}

// ===========================================================================
// ST-107 — Invariante de convergencia: único servicio, esquema común, procedencia preservada
// ===========================================================================
TEST_CASE("ST-107: Main Architectural Invariant - Single exporter, common schema, preserved provenance", "[integration][mode_to_export][ST-107]")
{
    IntegrationTempDirectory tempDir("st107_invariant");

    ReportExportRequest reqAuto;
    reqAuto.manifest.hardwareId = "AIRA_TB3";
    reqAuto.baseFileName = "TB3_Auto";
    reqAuto.destinationDirectory = tempDir.path / "tb3";
    reqAuto.options.includeProductionPackage = true;
    reqAuto.options.includeHtmlCertification = false;
    MeasuredPoint pa; pa.pointId = "PA"; reqAuto.measuredPoints.push_back(pa);

    ReportExportRequest reqManual;
    reqManual.manifest.hardwareId = "EURORACK_VCF";
    reqManual.baseFileName = "VCF_Manual";
    reqManual.destinationDirectory = tempDir.path / "vcf";
    reqManual.options.includeProductionPackage = true;
    reqManual.options.includeHtmlCertification = false;
    MeasuredPoint pm; pm.pointId = "PM"; reqManual.measuredPoints.push_back(pm);

    // Ambos son despachados hacia la ÚNICA autoridad de exportación: ReportExportService
    ReportExportResult resAuto = ReportExportService::exportReport(reqAuto);
    ReportExportResult resManual = ReportExportService::exportReport(reqManual);

    REQUIRE(resAuto.succeeded());
    REQUIRE(resManual.succeeded());

    // Invariante 1: Mismo número y tipo de artefactos obligatorios
    REQUIRE(resAuto.artifacts.size() == resManual.artifacts.size());

    // Invariante 2: Mismo schema de manifest
    auto autoManifest = tempDir.path / "tb3" / "TB3_Auto_manifest.json";
    auto manualManifest = tempDir.path / "vcf" / "VCF_Manual_manifest.json";
    REQUIRE(std::filesystem::exists(autoManifest));
    REQUIRE(std::filesystem::exists(manualManifest));

    std::ifstream ia(autoManifest);
    nlohmann::json ja = nlohmann::json::parse(ia);
    std::ifstream im(manualManifest);
    nlohmann::json jm = nlohmann::json::parse(im);

    REQUIRE(ja["sessionManifestVersion"] == jm["sessionManifestVersion"]);

    // Invariante 3: Procedencia metrológica diferenciada (no sobreescrita ni perdida)
    REQUIRE(ja["hardware"]["deviceType"] != jm["hardware"]["deviceType"]);
    REQUIRE(ja["hardware"]["deviceType"] == "AUTOMATED_SYSEX");
    REQUIRE(jm["hardware"]["deviceType"] == "MANUAL_EURORACK");
}
