/**
 * @file AudioABVerificationModal.cpp
 * @brief Implementation of AudioABVerificationModal.
 * @author ABDSynths
 * @date 2026
 */

#include "AudioABVerificationModal.h"
#include <cmath>
#include "../dsp/AnalogLutFilterModule.h"
#include "../dsp/OfficialLutModels.h"

namespace abdaudiolab::gui
{

AudioABVerificationModal::AudioABVerificationModal()
{
    formatManager.registerBasicFormats();
    setWantsKeyboardFocus(true);
    addKeyListener(this);

    // Panel container
    addChildComponent(panel);

    // Close button
    btnClose.setButtonText("X");
    btnClose.setColour(juce::TextButton::buttonColourId, juce::Colours::transparentBlack);
    btnClose.setColour(juce::TextButton::textColourOffId, SoundIdTheme::textSecondary);
    btnClose.onClick = [this] { dismissDialog(); };
    panel.addAndMakeVisible(btnClose);

    // Reference (A)
    lblRefTitle.setText("A: Physical Hardware (Reference)", juce::dontSendNotification);
    lblRefTitle.setFont(juce::FontOptions("Inter", 13.0f, juce::Font::bold));
    lblRefTitle.setColour(juce::Label::textColourId, SoundIdTheme::textPrimary);
    panel.addAndMakeVisible(lblRefTitle);

    lblRefInfo.setText("No signal loaded", juce::dontSendNotification);
    lblRefInfo.setFont(juce::FontOptions("Inter", 11.5f, juce::Font::plain));
    lblRefInfo.setColour(juce::Label::textColourId, SoundIdTheme::textSecondary);
    panel.addAndMakeVisible(lblRefInfo);

    btnLoadRef.setTooltip("Load reference .wav captured from physical synthesizer");
    btnLoadRef.setColour(juce::TextButton::buttonColourId, SoundIdTheme::bgCardHover);
    btnLoadRef.setColour(juce::TextButton::textColourOffId, SoundIdTheme::textPrimary);
    btnLoadRef.onClick = [this] { loadAudioFile(true); };
    panel.addAndMakeVisible(btnLoadRef);

    // Candidate (B)
    lblCandTitle.setText("B: Grey-Box DSP Emulation (Candidate)", juce::dontSendNotification);
    lblCandTitle.setFont(juce::FontOptions("Inter", 13.0f, juce::Font::bold));
    lblCandTitle.setColour(juce::Label::textColourId, SoundIdTheme::textPrimary);
    panel.addAndMakeVisible(lblCandTitle);

    lblCandInfo.setText("No signal loaded", juce::dontSendNotification);
    lblCandInfo.setFont(juce::FontOptions("Inter", 11.5f, juce::Font::plain));
    lblCandInfo.setColour(juce::Label::textColourId, SoundIdTheme::textSecondary);
    panel.addAndMakeVisible(lblCandInfo);

    btnLoadCand.setTooltip("Load candidate .wav generated by DSP plugin or LUT evaluator");
    btnLoadCand.setColour(juce::TextButton::buttonColourId, SoundIdTheme::bgCardHover);
    btnLoadCand.setColour(juce::TextButton::textColourOffId, SoundIdTheme::textPrimary);
    btnLoadCand.onClick = [this] { loadAudioFile(false); };
    panel.addAndMakeVisible(btnLoadCand);

    // DSP Model selector combo
    comboLutModel.addItem("Moog Ladder 24dB (lut_mock_va_synth)", 1);
    comboLutModel.addItem("Roland Juno-106 IR3109 VCF", 2);
    comboLutModel.addItem("Casio CZ-101 Phase Distortion", 3);
    comboLutModel.addItem("Behringer PRO-800 CEM3320 VCF", 4);
    comboLutModel.addItem("Eurorack Diode Ladder VCF", 5);
    comboLutModel.addItem("Roland AIRA Bitrazer Filter", 6);
    comboLutModel.setSelectedId(1, juce::dontSendNotification);
    panel.addAndMakeVisible(comboLutModel);

    btnSynthCandidate.setTooltip("Synthesize candidate directly from selected DSP grey-box LUT model using Ref signal");
    btnSynthCandidate.setColour(juce::TextButton::buttonColourId, SoundIdTheme::bgCardHover);
    btnSynthCandidate.setColour(juce::TextButton::textColourOffId, SoundIdTheme::accentGreen);
    btnSynthCandidate.onClick = [this] { synthesizeCandidateFromModel(); };
    panel.addAndMakeVisible(btnSynthCandidate);

    // Tolerance preset combo
    lblToleranceTitle.setText("Tolerance Profile:", juce::dontSendNotification);
    lblToleranceTitle.setFont(juce::FontOptions("Inter", 12.0f, juce::Font::bold));
    lblToleranceTitle.setColour(juce::Label::textColourId, SoundIdTheme::textPrimary);
    panel.addAndMakeVisible(lblToleranceTitle);

    comboTolerance.addItem(juce::String::fromUTF8(u8"Standard (Analog Corridor \u00b11\u03c3, Rxy \u2265 0.92, \u0394 \u2264 3.0 dB)"), 1);
    comboTolerance.addItem(juce::String::fromUTF8(u8"Strict (Mastering Grade, Rxy \u2265 0.98, \u0394 \u2264 1.5 dB)"), 2);
    comboTolerance.addItem(juce::String::fromUTF8(u8"Permissive (Envelope & Shape, Rxy \u2265 0.85, \u0394 \u2264 6.0 dB)"), 3);
    comboTolerance.setSelectedId(1, juce::dontSendNotification);
    panel.addAndMakeVisible(comboTolerance);

    // Action button
    btnRunVerify.setTooltip("Execute time-alignment cross-correlation and spectral verification");
    btnRunVerify.setColour(juce::TextButton::buttonColourId, SoundIdTheme::accentGreen);
    btnRunVerify.setColour(juce::TextButton::textColourOffId, juce::Colours::white);
    btnRunVerify.onClick = [this] { runComparison(); };
    panel.addAndMakeVisible(btnRunVerify);

    btnExportReport.setTooltip("Export complete verification results and metrics to JSON file");
    btnExportReport.setColour(juce::TextButton::buttonColourId, SoundIdTheme::bgCard);
    btnExportReport.setColour(juce::TextButton::textColourOffId, SoundIdTheme::textPrimary);
    btnExportReport.setEnabled(false);
    btnExportReport.onClick = [this] { exportReportJson(); };
    panel.addAndMakeVisible(btnExportReport);

    // Verdict Banner
    lblVerdictBadge.setText("NOT EVALUATED", juce::dontSendNotification);
    lblVerdictBadge.setFont(juce::FontOptions("Inter", 14.0f, juce::Font::bold));
    lblVerdictBadge.setJustificationType(juce::Justification::centred);
    lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xffe5e7eb));
    lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xff4b5563));
    panel.addAndMakeVisible(lblVerdictBadge);

    lblVerdictSummary.setText("Load both signals and click 'Run Verification' to contrast audio models.", juce::dontSendNotification);
    lblVerdictSummary.setFont(juce::FontOptions("Inter", 12.0f, juce::Font::plain));
    lblVerdictSummary.setJustificationType(juce::Justification::centred);
    lblVerdictSummary.setColour(juce::Label::textColourId, SoundIdTheme::textSecondary);
    panel.addAndMakeVisible(lblVerdictSummary);

    // Initial metrics text placeholders
    metricsTimeText = "Time Alignment\n\n\u2022 Peak Correlation (Rxy): --\n\u2022 Sample Offset: --\n\u2022 Latency Offset: --";
    metricsDynamicsText = "Dynamics & Energy\n\n\u2022 RMS Delta: -- dB\n\u2022 Peak Delta: -- dB\n\u2022 Residual RMS: -- dB";
    metricsSpectralText = "Spectral Conformity\n\n\u2022 Mean FFT Abs Diff: -- dB\n\u2022 Centroid Drift: -- Hz\n\u2022 Bands (L / M / H): --";
}

AudioABVerificationModal::~AudioABVerificationModal()
{
    removeKeyListener(this);
}

void AudioABVerificationModal::showDialog(juce::Component* parent)
{
    if (parent != nullptr)
    {
        parent->addChildComponent(this);
        setBounds(parent->getLocalBounds());
        setVisible(true);
        panel.setVisible(true);
        toFront(true);
    }
}

void AudioABVerificationModal::dismissDialog()
{
    setVisible(false);
}

bool AudioABVerificationModal::keyPressed(const juce::KeyPress& key, juce::Component*)
{
    return keyPressed(key);
}

bool AudioABVerificationModal::keyPressed(const juce::KeyPress& key)
{
    if (key == juce::KeyPress::escapeKey)
    {
        dismissDialog();
        return true;
    }
    return false;
}

void AudioABVerificationModal::mouseDown(const juce::MouseEvent& e)
{
    if (!panel.getBounds().contains(e.getPosition()))
    {
        dismissDialog();
    }
}

void AudioABVerificationModal::setReferenceSignal(const juce::AudioBuffer<float>& buffer, double sampleRate, const juce::String& label)
{
    refSignal.sampleRate = sampleRate;
    refSignal.numChannels = buffer.getNumChannels();
    refSignal.originalNumSamples = buffer.getNumSamples();
    refSignal.buffer.makeCopyOf(buffer);
    refName = label;

    double durationMs = (sampleRate > 0.0) ? (buffer.getNumSamples() * 1000.0 / sampleRate) : 0.0;
    lblRefInfo.setText(label + " | " + juce::String(sampleRate, 0) + " Hz | " + 
                       juce::String(buffer.getNumSamples()) + " spls (" + juce::String(durationMs, 1) + " ms)", 
                       juce::dontSendNotification);
}

void AudioABVerificationModal::setCandidateSignal(const juce::AudioBuffer<float>& buffer, double sampleRate, const juce::String& label)
{
    candSignal.sampleRate = sampleRate;
    candSignal.numChannels = buffer.getNumChannels();
    candSignal.originalNumSamples = buffer.getNumSamples();
    candSignal.buffer.makeCopyOf(buffer);
    candName = label;

    double durationMs = (sampleRate > 0.0) ? (buffer.getNumSamples() * 1000.0 / sampleRate) : 0.0;
    lblCandInfo.setText(label + " | " + juce::String(sampleRate, 0) + " Hz | " + 
                        juce::String(buffer.getNumSamples()) + " spls (" + juce::String(durationMs, 1) + " ms)", 
                        juce::dontSendNotification);
}

void AudioABVerificationModal::loadAudioFile(bool isReference)
{
    fileChooser = std::make_unique<juce::FileChooser>(
        isReference ? "Select Reference Audio File (Hardware)..." : "Select Candidate Audio File (Model)...",
        juce::File::getCurrentWorkingDirectory(),
        "*.wav;*.aif;*.aiff;*.flac");

    fileChooser->launchAsync(juce::FileBrowserComponent::openMode | juce::FileBrowserComponent::canSelectFiles,
        [this, isReference](const juce::FileChooser& fc) {
            auto file = fc.getResult();
            if (!file.existsAsFile()) return;

            std::unique_ptr<juce::AudioFormatReader> reader(formatManager.createReaderFor(file));
            if (reader == nullptr)
            {
                juce::AlertWindow::showMessageBoxAsync(juce::AlertWindow::WarningIcon, "File Error", "Could not decode audio file.");
                return;
            }

            juce::AudioBuffer<float> buf(static_cast<int>(reader->numChannels), static_cast<int>(reader->lengthInSamples));
            reader->read(&buf, 0, static_cast<int>(reader->lengthInSamples), 0, true, true);

            if (isReference)
                setReferenceSignal(buf, reader->sampleRate, file.getFileName());
            else
                setCandidateSignal(buf, reader->sampleRate, file.getFileName());
        });
}

void AudioABVerificationModal::synthesizeCandidateFromModel()
{
    if (refSignal.buffer.getNumSamples() == 0)
    {
        lblVerdictBadge.setText("ERROR: NO REF SIGNAL", juce::dontSendNotification);
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffee2e2));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xffdc2626));
        lblVerdictSummary.setText("Please load or measure a Reference signal (A) first to serve as excitation.", juce::dontSendNotification);
        repaint();
        return;
    }

    // Create a copy of the reference audio to process through the model
    juce::AudioBuffer<float> outputBuffer;
    outputBuffer.makeCopyOf(refSignal.buffer);

    // Initialize DSP AnalogLutFilterModule
    dsp::AnalogLutFilterModule filterModule;
    filterModule.setSmoothingTime(5.0, refSignal.sampleRate);
    filterModule.setVoiceParameters(0, 0.65f, 0.45f); // Nominal musical operating point

    const int numSamples = outputBuffer.getNumSamples();
    float* channelData = outputBuffer.getWritePointer(0);

    int modelId = comboLutModel.getSelectedId();
    juce::String modelLabel = comboLutModel.getText();

    // Map selection to official LUT array and grid size (8x8 = 64)
    const int gridSize = 8;
    const dsp::AbdBatchedPoint* lutPtr = dsp::models::mock_va_synth_moog_ladder;
    if (modelId == 2) lutPtr = dsp::models::roland_juno106_ir3109_vcf;
    else if (modelId == 3) lutPtr = dsp::models::casio_cz101_phase_distortion_resonant;
    else if (modelId == 4) lutPtr = dsp::models::behringer_pro800_cem3320_vcf;
    else if (modelId == 5) lutPtr = dsp::models::manual_eurorack_vcf_diode_ladder;
    else if (modelId == 6) lutPtr = dsp::models::roland_aira_bitrazer_filter;

    // Process in blocks of 64
    const int blockSize = 64;
    for (int offset = 0; offset < numSamples; offset += blockSize)
    {
        int curBlock = std::min(blockSize, numSamples - offset);
        float* blockPtr = channelData + offset;
        std::array<float*, 8> voicePtrs = { blockPtr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
        filterModule.processPolyphonicBlock(voicePtrs.data(), curBlock, lutPtr, gridSize);
    }

    // If stereo, copy processed channel 0 to channel 1
    if (outputBuffer.getNumChannels() > 1)
    {
        outputBuffer.copyFrom(1, 0, outputBuffer, 0, 0, numSamples);
    }

    setCandidateSignal(outputBuffer, refSignal.sampleRate, "DSP Model: " + modelLabel);
    updateVerdictUi();
}

void AudioABVerificationModal::runComparison()
{
    if (refSignal.buffer.getNumSamples() == 0 || candSignal.buffer.getNumSamples() == 0)
    {
        lblVerdictBadge.setText("ERROR: MISSING SIGNAL", juce::dontSendNotification);
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffee2e2));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xffdc2626));
        lblVerdictSummary.setText("Please load both Reference (A) and Candidate (B) signals before verifying.", juce::dontSendNotification);
        repaint();
        return;
    }

    if (std::abs(refSignal.sampleRate - candSignal.sampleRate) > 1.0)
    {
        lblVerdictBadge.setText("ERROR: RATE MISMATCH", juce::dontSendNotification);
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffee2e2));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xffdc2626));
        lblVerdictSummary.setText("Sample rates differ (Ref: " + juce::String(refSignal.sampleRate, 0) + 
                                  " Hz, Cand: " + juce::String(candSignal.sampleRate, 0) + " Hz). Resampling required.", 
                                  juce::dontSendNotification);
        repaint();
        return;
    }

    math::AudioABRunContext ctx;
    ctx.runId = "ab-verify-interactive";

    math::AudioABComparatorConfig config;
    config.trimLeadingSilence = true;
    config.trimTrailingSilence = true;

    math::AudioABComparator comparator;
    lastResult = comparator.compare(refSignal, candSignal, ctx, config);

    if (lastResult.status != "ok")
    {
        lblVerdictBadge.setText("COMPARISON FAILED", juce::dontSendNotification);
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffee2e2));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xffdc2626));
        lblVerdictSummary.setText("Engine error: " + juce::String(lastResult.status), juce::dontSendNotification);
        repaint();
        return;
    }

    // Configure tolerances according to combo
    math::AudioABVerdictTolerances tolerances;
    int selectedPreset = comboTolerance.getSelectedId();
    if (selectedPreset == 2) // Strict
    {
        tolerances.minCorrelationPeak = 0.98;
        tolerances.maxRmsDeltaDb = 1.0;
        tolerances.maxSpectralDeltaDb = 1.5;
        tolerances.maxSampleOffset = 128.0;
        tolerances.minOverlapRatio = 0.98;
    }
    else if (selectedPreset == 3) // Permissive
    {
        tolerances.minCorrelationPeak = 0.85;
        tolerances.maxRmsDeltaDb = 4.0;
        tolerances.maxSpectralDeltaDb = 5.0;
        tolerances.maxSampleOffset = 1024.0;
        tolerances.minOverlapRatio = 0.90;
    }
    else // Standard (Default ±1σ)
    {
        tolerances.minCorrelationPeak = 0.92;
        tolerances.maxRmsDeltaDb = 2.0;
        tolerances.maxSpectralDeltaDb = 3.0;
        tolerances.maxSampleOffset = 512.0;
        tolerances.minOverlapRatio = 0.95;
    }

    math::AudioABVerdictEngine verdictEngine;
    lastVerdict = verdictEngine.evaluate(lastResult, tolerances);
    hasResult = true;
    btnExportReport.setEnabled(true);

    updateVerdictUi();

    if (onVerificationCompleted != nullptr)
        onVerificationCompleted(lastResult, lastVerdict);

    repaint();
}

void AudioABVerificationModal::updateVerdictUi()
{
    juce::String levelUpper = juce::String(lastVerdict.level).toUpperCase();
    lblVerdictBadge.setText(levelUpper, juce::dontSendNotification);

    if (levelUpper == "PASS")
    {
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xffd1fae5));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xff065f46));
    }
    else if (levelUpper == "WARN")
    {
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffef3c7));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xff92400e));
    }
    else
    {
        lblVerdictBadge.setColour(juce::Label::backgroundColourId, juce::Colour(0xfffee2e2));
        lblVerdictBadge.setColour(juce::Label::textColourId, juce::Colour(0xff991b1b));
    }

    juce::String ruleText = lastVerdict.triggeredRules.isEmpty() ? "" : (" (" + lastVerdict.triggeredRules.joinIntoString(", ") + ")");
    lblVerdictSummary.setText(juce::String(lastVerdict.reasonCode) + ruleText, juce::dontSendNotification);

    // Format metrics text
    metricsTimeText = juce::String::fromUTF8(u8"TIME ALIGNMENT\n\n")
        + juce::String::fromUTF8(u8"• Peak Correlation: ") + juce::String(lastResult.alignment.correlationPeak, 4) + "\n"
        + juce::String::fromUTF8(u8"• Sample Offset: ") + juce::String(lastResult.alignment.sampleOffset) + " samples\n"
        + juce::String::fromUTF8(u8"• Time Offset: ") + juce::String(lastResult.alignment.timeOffsetMs, 2) + " ms\n"
        + juce::String::fromUTF8(u8"• Overlap Ratio: ") + juce::String(lastResult.alignment.overlapRatio * 100.0, 1) + "%";

    metricsDynamicsText = juce::String::fromUTF8(u8"DYNAMICS & ENERGY\n\n")
        + juce::String::fromUTF8(u8"• RMS Delta: ") + juce::String(lastResult.time.rmsDeltaDb, 2) + " dB\n"
        + juce::String::fromUTF8(u8"• Peak Delta: ") + juce::String(lastResult.time.peakDeltaDb, 2) + " dB\n"
        + juce::String::fromUTF8(u8"• Residual RMS: ") + juce::String(lastResult.time.residualRmsDbfs, 1) + " dBfs\n"
        + juce::String::fromUTF8(u8"• Residual Peak: ") + juce::String(lastResult.time.residualPeakDbfs, 1) + " dBfs";

    metricsSpectralText = juce::String::fromUTF8(u8"SPECTRAL CONFORMITY\n\n")
        + juce::String::fromUTF8(u8"• Mean FFT Diff: ") + juce::String(lastResult.spectral.logMagMeanAbsDiffDb, 2) + " dB\n"
        + juce::String::fromUTF8(u8"• Centroid Drift: ") + juce::String(lastResult.spectral.spectralCentroidDeltaHz, 1) + " Hz\n"
        + juce::String::fromUTF8(u8"• Low Band \u0394: ") + juce::String(lastResult.spectral.lowBandDeltaDb, 2) + " dB\n"
        + juce::String::fromUTF8(u8"• Mid Band \u0394: ") + juce::String(lastResult.spectral.midBandDeltaDb, 2) + " dB\n"
        + juce::String::fromUTF8(u8"• High Band \u0394: ") + juce::String(lastResult.spectral.highBandDeltaDb, 2) + " dB";
}

void AudioABVerificationModal::exportReportJson()
{
    if (!hasResult) return;

    fileChooser = std::make_unique<juce::FileChooser>(
        "Save A/B Verification Report...",
        juce::File::getCurrentWorkingDirectory().getChildFile("ab_verification_report.json"),
        "*.json");

    fileChooser->launchAsync(juce::FileBrowserComponent::saveMode | juce::FileBrowserComponent::canSelectFiles,
        [this](const juce::FileChooser& fc) {
            auto file = fc.getResult();
            if (file.getFileExtension().isEmpty())
                file = file.withFileExtension("json");

            juce::DynamicObject::Ptr root = new juce::DynamicObject();
            root->setProperty("title", "ABDAudioLab A/B Model Verification Report");
            root->setProperty("reference", refName);
            root->setProperty("candidate", candName);

            juce::DynamicObject::Ptr verdictObj = new juce::DynamicObject();
            verdictObj->setProperty("level", juce::String(lastVerdict.level));
            verdictObj->setProperty("reasonCode", juce::String(lastVerdict.reasonCode));
            verdictObj->setProperty("triggeredRules", lastVerdict.triggeredRules.joinIntoString(", "));
            root->setProperty("verdict", juce::var(verdictObj.get()));

            juce::DynamicObject::Ptr alignObj = new juce::DynamicObject();
            alignObj->setProperty("correlationPeak", lastResult.alignment.correlationPeak);
            alignObj->setProperty("sampleOffset", lastResult.alignment.sampleOffset);
            alignObj->setProperty("timeOffsetMs", lastResult.alignment.timeOffsetMs);
            alignObj->setProperty("overlapRatio", lastResult.alignment.overlapRatio);
            root->setProperty("alignment", juce::var(alignObj.get()));

            juce::DynamicObject::Ptr timeObj = new juce::DynamicObject();
            timeObj->setProperty("rmsDeltaDb", lastResult.time.rmsDeltaDb);
            timeObj->setProperty("peakDeltaDb", lastResult.time.peakDeltaDb);
            timeObj->setProperty("residualRmsDbfs", lastResult.time.residualRmsDbfs);
            timeObj->setProperty("residualPeakDbfs", lastResult.time.residualPeakDbfs);
            timeObj->setProperty("rmse", lastResult.time.rmse);
            root->setProperty("dynamics", juce::var(timeObj.get()));

            juce::DynamicObject::Ptr specObj = new juce::DynamicObject();
            specObj->setProperty("logMagMeanAbsDiffDb", lastResult.spectral.logMagMeanAbsDiffDb);
            specObj->setProperty("spectralCentroidDeltaHz", lastResult.spectral.spectralCentroidDeltaHz);
            specObj->setProperty("lowBandDeltaDb", lastResult.spectral.lowBandDeltaDb);
            specObj->setProperty("midBandDeltaDb", lastResult.spectral.midBandDeltaDb);
            specObj->setProperty("highBandDeltaDb", lastResult.spectral.highBandDeltaDb);
            root->setProperty("spectral", juce::var(specObj.get()));

            juce::var jsonVar(root.get());
            juce::String jsonText = juce::JSON::toString(jsonVar, true);
            file.replaceWithText(jsonText);
        });
}

void AudioABVerificationModal::paint(juce::Graphics& g)
{
    // Scrim overlay
    g.fillAll(juce::Colour(0x75000000));

    // Panel background
    auto panelBounds = panel.getBounds();
    g.setColour(SoundIdTheme::bgLight);
    g.fillRoundedRectangle(panelBounds.toFloat(), 10.0f);
    g.setColour(SoundIdTheme::borderSubtle);
    g.drawRoundedRectangle(panelBounds.toFloat(), 10.0f, 1.5f);

    // Header Title and Subtitle
    g.setColour(SoundIdTheme::textPrimary);
    g.setFont(juce::FontOptions("Inter", 16.0f, juce::Font::bold));
    g.drawText("A/B Model Verification & Spectral Correlation", panelBounds.getX() + 24, panelBounds.getY() + 16, panelBounds.getWidth() - 70, 22, juce::Justification::centredLeft);

    g.setColour(SoundIdTheme::textSecondary);
    g.setFont(juce::FontOptions("Inter", 12.0f, juce::Font::plain));
    g.drawText("Contrast physical hardware capture against grey-box DSP emulation under ISO/EBU tolerances", 
               panelBounds.getX() + 24, panelBounds.getY() + 38, panelBounds.getWidth() - 70, 18, juce::Justification::centredLeft);

    // Divider line
    g.setColour(SoundIdTheme::borderSubtle);
    g.fillRect(panelBounds.getX() + 24, panelBounds.getY() + 60, panelBounds.getWidth() - 48, 1);

    // Cards rects inside panel
    int cardY = panelBounds.getY() + 310;
    int cardH = panelBounds.getBottom() - cardY - 24;
    int cardW = (panelBounds.getWidth() - 48 - 24) / 3;

    for (int i = 0; i < 3; ++i)
    {
        juce::Rectangle<int> card(panelBounds.getX() + 24 + i * (cardW + 12), cardY, cardW, cardH);
        g.setColour(SoundIdTheme::bgCard);
        g.fillRoundedRectangle(card.toFloat(), 6.0f);
        g.setColour(SoundIdTheme::borderSubtle);
        g.drawRoundedRectangle(card.toFloat(), 6.0f, 1.0f);

        g.setColour(SoundIdTheme::textPrimary);
        g.setFont(juce::FontOptions("Inter", 11.5f, juce::Font::plain));
        
        juce::String textToDraw;
        if (i == 0) textToDraw = metricsTimeText;
        else if (i == 1) textToDraw = metricsDynamicsText;
        else textToDraw = metricsSpectralText;

        g.drawFittedText(textToDraw, card.reduced(12, 10), juce::Justification::topLeft, 8);
    }
}

void AudioABVerificationModal::resized()
{
    int w = std::min(780, getWidth() - 40);
    int h = std::min(580, getHeight() - 40);
    panel.setBounds((getWidth() - w) / 2, (getHeight() - h) / 2, w, h);

    // Layout within panel
    btnClose.setBounds(panel.getWidth() - 36, 12, 24, 24);

    int y = 20;
    // Header title rendered in custom paint of panel
    y += 45;

    // Reference & Candidate rows
    int rowW = (panel.getWidth() - 48 - 16) / 2;
    lblRefTitle.setBounds(24, y, rowW, 20);
    lblCandTitle.setBounds(24 + rowW + 16, y, rowW, 20);
    y += 22;

    lblRefInfo.setBounds(24, y, rowW, 18);
    lblCandInfo.setBounds(24 + rowW + 16, y, rowW, 18);
    y += 24;

    btnLoadRef.setBounds(24, y, rowW, 30);
    btnLoadCand.setBounds(24 + rowW + 16, y, rowW / 2 - 4, 30);
    comboLutModel.setBounds(24 + rowW + 16 + rowW / 2, y, rowW / 2, 30);
    y += 34;

    btnSynthCandidate.setBounds(24 + rowW + 16, y, rowW, 26);
    y += 34;

    // Tolerance Preset
    lblToleranceTitle.setBounds(24, y, 120, 28);
    comboTolerance.setBounds(150, y, panel.getWidth() - 174, 28);
    y += 36;

    // Action Buttons
    int btnW = 220;
    btnRunVerify.setBounds(24, y, btnW, 36);
    btnExportReport.setBounds(24 + btnW + 12, y, 180, 36);
    y += 48;

    // Verdict Banner
    lblVerdictBadge.setBounds(24, y, 160, 30);
    lblVerdictSummary.setBounds(196, y, panel.getWidth() - 220, 30);
}

} // namespace abdaudiolab::gui
